# use ubuntu linux.
os: linux
dist: trusty

# run in container.
sudo: required

# use nodejs environment.
language: node_js
node_js: stable

# install stable chrome and firefox.
addons:
  chrome: stable
  firefox: latest
  sauce_connect: false
  apt:
    packages:
      - oracle-java8-set-default

# run npm and bower install.
before_script:
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm install --global bower
  - npm install
  - bower install --force-latest

# run npm build.
script:
  - npm run build
  - npm run lint
  - npm run test
